const LessonsActionType = {
  FETCH_ALL_LESSONS: "FETCH_ALL_LESSONS",
  FETCH_SINGLE_LESSON: "FETCH_SINGLE_LESSON",
  ADD_LESSON: "ADD_LESSON",
  EDIT_LESSON: "EDIT_LESSON",
};
export default LessonsActionType;